# Generated by Django 6.0.4 on 2026-04-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso corporal (kg)')),
                ('weight_class_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Categoria de peso (kg)')),
                ('equipment', models.CharField(choices=[('raw', 'Clássica (Raw)'), ('equipped', 'Equipado (Multiply)')], default='raw', max_length=20)),
                ('federation', models.CharField(choices=[('IPF', 'IPF'), ('CBLB', 'CBLB'), ('other', 'Outra')], default='CBLB', max_length=20)),
                ('best_squat_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Melhor agachamento (kg)')),
                ('best_bench_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Melhor supino (kg)')),
                ('best_deadlift_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Melhor terra (kg)')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='Treinador(a) responsável')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de atleta',
                'verbose_name_plural': 'Perfis de atleta',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainer', 'Treinador(a)'), ('athlete', 'Atleta')], default='athlete', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
