# Generated by Django 6.0.4 on 2026-04-24 16:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('tier', models.CharField(choices=[('principal', 'Principal (SBD)'), ('primary_var', 'Primeira ordem (variação)'), ('accessory', 'Acessório')], default='accessory', max_length=20, verbose_name='Classificação')),
                ('main_lift', models.CharField(choices=[('squat', 'Agachamento'), ('bench', 'Supino'), ('deadlift', 'Terra'), ('none', 'Outro / Acessório')], default='none', help_text="Usado na tonelagem. Ex.: supino fechado tem movimento-pai 'Supino'.", max_length=20, verbose_name='Movimento-pai')),
                ('cues', models.TextField(blank=True, verbose_name='Cues técnicos')),
                ('video_url', models.URLField(blank=True, verbose_name='Vídeo demonstrativo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Biblioteca de exercícios',
                'ordering': ['tier', 'main_lift', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título (opcional)')),
                ('scheduled_date', models.DateField(verbose_name='Data')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('notes', models.TextField(blank=True, verbose_name='Notas do treinador')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['scheduled_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AthleteAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('years_training', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anos de treino com carga')),
                ('years_competing', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anos competindo')),
                ('best_meet_total', models.CharField(blank=True, max_length=120, verbose_name='Melhor total em competição')),
                ('injuries', models.TextField(blank=True, verbose_name='Lesões passadas ou em curso')),
                ('limitations', models.TextField(blank=True, verbose_name='Limitações de movimento')),
                ('medical_history', models.TextField(blank=True, verbose_name='Histórico médico')),
                ('training_goal', models.TextField(blank=True, verbose_name='Meta do ciclo')),
                ('observations', models.TextField(blank=True, verbose_name='Outras observações')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anamneses', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anamneses_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do template')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='Séries')),
                ('reps', models.CharField(blank=True, max_length=20, verbose_name='Reps')),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Carga (kg)')),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='RPE alvo')),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90, verbose_name='Descanso (s)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_templates', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exerciselibrary')),
            ],
            options={
                'verbose_name': 'Template de acessório',
                'verbose_name_plural': 'Templates de acessórios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Carga (kg)')),
                ('reps', models.PositiveSmallIntegerField(default=1, verbose_name='Repetições')),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('context', models.CharField(choices=[('training', 'Treino'), ('meet', 'Competição')], default='training', max_length=20)),
                ('meet_name', models.CharField(blank=True, max_length=150, verbose_name='Nome da competição')),
                ('video_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exerciselibrary')),
            ],
            options={
                'verbose_name': 'PR',
                'verbose_name_plural': 'PRs',
                'ordering': ['-date', '-weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do plano')),
                ('goal', models.CharField(blank=True, max_length=200, verbose_name='Objetivo')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Início')),
                ('meet_date', models.DateField(blank=True, null=True, verbose_name='Data da competição')),
                ('weekly_frequency', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Treinos por semana')),
                ('general_notes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_as_athlete', to=settings.AUTH_USER_MODEL, verbose_name='Atleta')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Treinador(a)')),
            ],
            options={
                'verbose_name': 'Plano de treino',
                'verbose_name_plural': 'Planos de treino',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('had_pain', models.BooleanField(default=False, verbose_name='Sentiu dor?')),
                ('pain_description', models.CharField(blank=True, max_length=200, verbose_name='Onde/como foi a dor?')),
                ('was_tired', models.BooleanField(default=False, verbose_name='Estava cansado?')),
                ('tired_description', models.CharField(blank=True, max_length=200, verbose_name='Do que veio o cansaço?')),
                ('session_rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE geral da sessão (1–10)')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Horas de sono na noite anterior')),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso do dia (kg)')),
                ('general_notes', models.TextField(blank=True, verbose_name='Alguma observação extra?')),
                ('trainer_response', models.TextField(blank=True, verbose_name='Resposta do treinador')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='training.trainingsession')),
            ],
            options={
                'verbose_name': 'Feedback de sessão',
                'verbose_name_plural': 'Feedbacks de sessão',
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('planned_sets', models.PositiveSmallIntegerField(default=3, verbose_name='Séries')),
                ('planned_reps', models.CharField(blank=True, help_text='Ex.: 5, 3-5, 8×2', max_length=20, verbose_name='Reps')),
                ('planned_load_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% do 1RM')),
                ('reference_1rm_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='1RM de referência (kg)')),
                ('planned_load_kg_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Para acessórios, informe a carga direta.', max_digits=7, null=True, verbose_name='Carga prevista (kg)')),
                ('planned_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='RPE alvo')),
                ('rest_seconds', models.PositiveSmallIntegerField(default=180, verbose_name='Descanso (s)')),
                ('actual_load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Carga feita (kg)')),
                ('actual_reps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reps executadas (por série)')),
                ('actual_sets', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Séries completadas')),
                ('actual_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='RPE real')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exerciselibrary')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='training.trainingsession')),
            ],
            options={
                'verbose_name': 'Exercício da sessão',
                'verbose_name_plural': 'Exercícios da sessão',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(verbose_name='Semana')),
                ('start_date', models.DateField(verbose_name='Início da semana')),
                ('end_date', models.DateField(verbose_name='Fim da semana')),
                ('block_type', models.CharField(choices=[('accumulation', 'Acumulação'), ('intensification', 'Intensificação'), ('peaking', 'Peaking'), ('deload', 'Deload'), ('test', 'Teste de máximas')], default='accumulation', max_length=20, verbose_name='Tipo de bloco')),
                ('focus', models.CharField(blank=True, max_length=150, verbose_name='Foco')),
                ('notes', models.TextField(blank=True, verbose_name='Notas da semana')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.trainingplan')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'ordering': ['week_number'],
                'unique_together': {('plan', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingweek'),
        ),
    ]
