# Generated by Django 6.0.4 on 2026-04-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='label',
            field=models.CharField(blank=True, help_text="Ex.: 'A', 'B', 'C'. Aparece como 'TREINO A' no calendário.", max_length=20, verbose_name='Letra (A/B/C…)'),
        ),
        migrations.CreateModel(
            name='RepScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Ex.: '6×3', '3×10', '5×5'.", max_length=20, verbose_name='Padrão')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='Séries')),
                ('reps', models.CharField(max_length=20, verbose_name='Reps')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão favorito')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esquema de reps',
                'verbose_name_plural': 'Esquemas de reps',
                'ordering': ['-is_default', 'label'],
                'unique_together': {('trainer', 'label')},
            },
        ),
    ]
